# Generated by Django 3.2.4 on 2022-10-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspointage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='view_authorisation',
            field=models.BooleanField(default=False),
        ),
    ]
