# Generated by Django 3.2.4 on 2022-10-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspointage', '0002_role_view_authorisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='horairejour',
            name='margeheuresupp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
