# Generated by Django 3.2.4 on 2022-10-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syspointage', '0004_arborescence_directeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arborescence',
            name='directeur',
        ),
    ]
