# Generated by Django 3.2.4 on 2022-10-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspointage', '0005_remove_arborescence_directeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_DRH',
            field=models.BooleanField(default=False),
        ),
    ]
